import { Box } from "@mantine/core";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import ImagesGrid from "~/components/ImagesGrid";
import Layout from "~/components/Layout";
import { api } from "~/utils/api";

export default function Home() {
  const utils = api.useContext();

  return (
    <>
      <Head>
        <title>URPM</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="main">
        <Layout>
          <ImagesGrid onlyUser={false} onlyFavorite={false} />
        </Layout>
      </Box>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  return (
    <div>
      <p>{sessionData && <span>Logged in as {sessionData.user?.name}</span>}</p>
      <button
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
